services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_rt
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - nw_rt_01
    volumes:
      - postgres_rt_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d real_time_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_rt
    ports:
      - "6379:6379"
    networks:
      - nw_rt_01
    volumes:
      - redis_rt_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  nw_rt_01:

volumes:
  postgres_rt_data:
  redis_rt_data:
